development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: pubprika_development
  pool: 5
  username: pubprika
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: pubprika_test
  pool: 5
  username: pubprika
  password:
